import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import OfferCountdown from "@/components/OfferCountdown";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fitness & Beauty Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OfferCountdown />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
